overwritten checkout theme templates with confira styling
rapidez/confira pull request #3
Opened 2023-11-15 13:10 UTC by jordythevulder

2023-11-15 13:28 UTC, jordythevulder commented on resources/views/cart/overview.blade.php
> +            <x-rapidez-ct::layout class="[&>div:first-child>div>table]:my-0">
i've added this into the checkout theme as a PR, this is just for the timebeing. i will monitor the pullrequest, and if it gets merged i'll personally delete this.

2023-11-15 13:36 UTC, Roene-JustBetter requested changes

2023-11-15 13:36 UTC, Roene-JustBetter commented on resources/views/components/layout/checkout.blade.php
> +<div class="fixed -top-px h-1.5 left-0 right-0 w-full bg-primary z-20"></div>
`inset-x-0`

2023-11-15 13:36 UTC, Roene-JustBetter commented on resources/views/components/layout/checkout.blade.php
> +    <div class="flex flex-wrap lg:flex-row flex-col flex-1 max-lg:pt-6">
default flex behaviour is `flex-row` so you can change this to `max-lg:flex-col`

2023-11-15 13:36 UTC, Roene-JustBetter commented on resources/views/components/layout/index.blade.php
> +    <div class="flex flex-wrap lg:flex-row flex-col flex-1">
default flex behaviour is `flex-row `so you can change this to `max-lg:flex-col`

2023-11-15 14:12 UTC, Roene-JustBetter approved these changes

2023-11-16 08:16 UTC, royduin requested changes

2023-11-16 08:16 UTC, royduin commented on resources/views/components/card/inactive.blade.php
> +<div {{ $attributes->class('') }}>
```suggestion
<div {{ $attributes }}>
```

2023-11-16 08:16 UTC, royduin commented on resources/views/components/card/index.blade.php
> +<div {{ $attributes->class('') }}>
```suggestion
<div {{ $attributes }}>
```

2023-11-16 08:16 UTC, merged