Feature/v3 colors and tweaks
rapidez/confira pull request #31
Opened 2024-12-17 16:12 UTC by jordythevulder

Implemented v3 and various tweaks

2024-12-18 07:44 UTC, royduin requested changes

2024-12-18 07:44 UTC, royduin commented on resources/views/checkout/partials/buttons/address.blade.php
> +    <x-rapidez::button tag="label" for="popup" class="cursor-pointer" v-if="$root.user.addresses.length">
The if statement should be something else; have a look at the core.

2024-12-18 07:44 UTC, royduin commented on resources/views/checkout/partials/sections/success/product-quantity.blade.php
> +    <div class="h-12 w-16 border flex items-center rounded-md justify-center ring ring-background text-base">
Ok for now, internal reference: RAP-1079

2024-12-18 07:44 UTC, royduin commented on resources/views/checkout/partials/sections/success/summary.blade.php
> +        <dd class="font-mediuml">@{{ order.tax_amount | price }}</dd>
Typo?

2024-12-18 07:44 UTC, royduin commented on resources/views/checkout/partials/sidebar/products.blade.php
> +                <img v-if="item.product.image" class="max-h-20 w-20 shrink-0 object-contain mix-blend-darken bg-white" :alt="item.product.name" :src="'/storage/{{ config('rapidez.store') }}/resizes/2
Should this use the `resizedPath()` helper?

2024-12-18 07:44 UTC, royduin commented on resources/views/components/address-form.blade.php
> +            '!col-span-full sm:!col-span-3' => !Rapidez::config('customer/address/middlename_show', 0),
Toggling is cleaner than importants

2024-12-18 07:44 UTC, royduin commented on resources/views/components/address-form.blade.php
> +        ])
Toggling is cleaner than importants

2024-12-18 07:44 UTC, royduin commented on resources/views/components/input/checkbox/checkbox.blade.php
Do we still want/need a custom checkbox component? If it visually differs it's maybe better to have a variant.

2024-12-18 07:44 UTC, royduin commented on resources/views/components/input/checkbox/tile.blade.php
Maybe remove/refactor this one as well?

2024-12-18 07:44 UTC, royduin commented on resources/views/components/input/input.blade.php
Same, can we get rid of this?

2024-12-18 07:44 UTC, royduin commented on resources/views/components/input/label.blade.php
Before I comment on every input component; I think we should double check all of them.

2024-12-18 07:45 UTC, royduin commented
And the readme needs an update.

2024-12-18 09:01 UTC, JimmyHoenderdaal requested changes

2024-12-18 09:01 UTC, JimmyHoenderdaal commented on resources/views/cart/cart.blade.php
> +    <x-rapidez::button.outline href="/" class="max-lg:hidden !flex-none">
Why is this needed?

2024-12-18 09:21 UTC, Roene-JustBetter requested changes

2025-01-09 11:53 UTC, Roene-JustBetter requested changes

2025-01-09 11:53 UTC, Roene-JustBetter commented on resources/views/checkout/partials/sections/success/summary.blade.php
> +                    <span class="text-muted">@{{ item.name }}</span>
Parent has a `text-muted` why do you need it on the span as well?

2025-01-09 11:53 UTC, Roene-JustBetter commented on resources/views/checkout/steps/success.blade.php
> +                <x-rapidez-ct::card.inactive class="!bg-green-400/15 pb-8 px-7 !py-5 rounded-xl border-b border-black/5">
You can remove the `pb-8` here because it will never work when you have `!py-5`

2025-01-09 11:55 UTC, Roene-JustBetter commented on resources/views/components/input/input.blade.php
Why can't we use the input from the blade components?

2025-01-09 11:56 UTC, Roene-JustBetter commented on resources/views/components/input/password/password.blade.php
Check the rapidez/core there is an password component there as well.

2025-01-10 10:56 UTC, Roene-JustBetter requested changes

2025-01-10 10:56 UTC, Roene-JustBetter commented on resources/views/components/address-form.blade.php
> -            type="{{ Rapidez::config('customer/address/street_lines', 3) == 3 ? 'number' : 'text' }}"
This should be still on the input? `type="{{ Rapidez::config('customer/address/street_lines', 3) == 3 ? 'number' : 'text' }}"`

2025-01-13 08:47 UTC, jordythevulder commented on resources/views/components/address-form.blade.php
> -            type="{{ Rapidez::config('customer/address/street_lines', 3) == 3 ? 'number' : 'text' }}"
It's still on there! the file shifted a bit

2025-01-13 08:51 UTC, Roene-JustBetter submitted a review, later dismissed

2025-01-13 08:59 UTC, jordythevulder commented on resources/views/cart/cart.blade.php
> +    <x-rapidez::button.outline href="/" class="max-lg:hidden !flex-none">
Removed this! changed the base component

2025-01-13 13:01 UTC, Roene-JustBetter submitted a review, later dismissed

2025-01-14 08:35 UTC, JimmyHoenderdaal submitted a review, later dismissed

2025-01-14 11:06 UTC, royduin commented
Does it depend on a specific version of one of these?

- `rapidez/checkout-theme`
- `rapidez/core`
- `rapidez/blade-components`

The currently only dependency is: `"rapidez/checkout-theme": "^3.0"`, so with just `rapidez/checkout-theme` version 3.0.0 everything works?

2025-01-14 14:31 UTC, jordythevulder commented
> Does it depend on a specific version of one of these?
> 
> * `rapidez/checkout-theme`
> * `rapidez/core`
> * `rapidez/blade-components`
> 
> The currently only dependency is: `"rapidez/checkout-theme": "^3.0"`, so with just `rapidez/checkout-theme` version 3.0.0 everything works?

I've used these versions locally
Checkout theme dev-master as 3.0
Core dev-master as 3.0
Blade components dev-master as 1.2.0

2025-01-15 12:46 UTC, royduin commented
Let's wait for https://github.com/rapidez/checkout-theme/pull/160 to be merged and tagged as this depends on it.

2025-01-29 15:43 UTC, jordythevulder commented
Found a few classes that weren't necessary, also doubled checked. Looks good to me :)

2025-02-25 08:25 UTC, Roene-JustBetter commented
- Fixed merge conflict.
- Added sorting for country select.
- Checked translations and added / removed it.

With the fixes above this PR should be ready for merge 🚀

2025-02-25 08:25 UTC, Roene-JustBetter submitted a review, later dismissed

2025-02-26 07:34 UTC, royduin commented on resources/views/checkout/partials/address-cards-popup.blade.php
> +    <label class="absolute cursor-pointer inset-0 bg-black/60" for="popup"></label>
Is this a backdrop? In that case we do have a backdrop color for that.

2025-02-26 07:36 UTC, royduin commented on resources/views/checkout/partials/sections/success/summary.blade.php
> +    <dl v-if="order.grand_total" class="flex items-center order-last justify-between border-t border-dashed pt-3 mt-4">
Why do we need 2 dl's? Can't we have everything in one dl?

2025-02-26 07:37 UTC, royduin commented on resources/views/checkout/partials/shipping/methods.blade.php
> +            </x-rapidez-ct::input.radio.tile>
Is this indenting right?

2025-02-26 07:38 UTC, royduin commented on resources/views/checkout/partials/sidebar/products.blade.php
> +        <button v-if="cart.items.length > 2" class="flex items-center pb-1 gap-1 !border-t-0 !pt-0 hover:underline" @click="toggle">
Importants on a default button?

2025-02-26 07:39 UTC, royduin commented on resources/views/checkout/steps/success.blade.php
> +                <x-rapidez-ct::card.inactive class="!bg-green-400/15 px-7 !py-5 rounded-xl border-b border-black/5">
Aren't we using the Tailwind merging so we don't need any importants?

2025-02-26 07:43 UTC, royduin commented on resources/views/components/card/white.blade.php
> +<div {{ $attributes->class('relative flex-1 rounded-md border bg-white px-6 py-5 overflow-hidden ring ring-background') }}>
`ring-background`? Shouldn't that be `ring-muted`?

2025-02-26 07:43 UTC, royduin commented on resources/views/components/card/address-alt.blade.php
> +<x-rapidez-ct::card.white class="!border-0 !shadow-none !p-0 !ring-0" {{ $attributes->only('v-if') }}>
We need to add twMerge so we don't need the importants

2025-02-26 07:48 UTC, royduin commented on resources/views/checkout/partials/sections/success/product-quantity.blade.php
> +    <div class="h-12 w-16 border flex items-center rounded-md justify-center ring ring-background text-base">
This is within the core now, maybe search and replace all `-background`s?

2025-02-26 09:32 UTC, Roene-JustBetter commented on resources/views/checkout/partials/sidebar/products.blade.php
> +        <button v-if="cart.items.length > 2" class="flex items-center pb-1 gap-1 !border-t-0 !pt-0 hover:underline" @click="toggle">
Yes this is because of the wrapping `<div class="*:pt-2.5 first:*:pt-0 mb-2.5 flex w-full flex-col gap-2.5 divide-y divide-dashed border-b border-dashed pb-2.5">` that sets borders between the elements. 

The button here as you can see below doesn't need a border as that looks weird: 
<img width="361" alt="Scherm­afbeelding 2025-02-26 om 10 29 37" src="https://github.com/user-attachments/assets/e6f4437b-1a66-429d-a943-cf299ec06cb4" />
<img width="420" alt="Scherm­afbeelding 2025-02-26 om 10 31 30" src="https://github.com/user-attachments/assets/fa61567d-fb60-4424-9531-5159d3e75988" />

<img width="383" alt="Scherm­afbeelding 2025-02-26 om 10 29 56" src="https://github.com/user-attachments/assets/af7ea74b-a674-4eaa-8732-41c32df53580" />
<img width="360" alt="Scherm­afbeelding 2025-02-26 om 10 31 22" src="https://github.com/user-attachments/assets/60a9cde8-06f9-4e68-8dcb-d860107edb66" />

2025-02-26 09:49 UTC, Roene-JustBetter commented on resources/views/checkout/steps/success.blade.php
> +                <x-rapidez-ct::card.inactive class="!bg-green-400/15 px-7 !py-5 rounded-xl border-b border-black/5">
I checked the importants. For the background we don't need the !important so we can remove it. For the padding we need the important because of the wrapping parent `divide-y divide-dashed *:pt-6 *:mb-6 mt-5 mb-6 first:*:pt-0`.

2025-03-04 15:32 UTC, jordythevulder commented on resources/views/checkout/partials/sections/success/product-quantity.blade.php
> +    <div class="h-12 w-16 border flex items-center rounded-md justify-center ring ring-background text-base">
Yes changed ring-background > ring-muted

2025-03-04 15:33 UTC, jordythevulder commented on resources/views/checkout/partials/sections/success/summary.blade.php
> +    <dl v-if="order.grand_total" class="flex items-center order-last justify-between border-t border-dashed pt-3 mt-4">
Since the v3 update that whole file wasn't even used. Double checked on frontend still looks good on succes page.

2025-03-04 15:33 UTC, jordythevulder commented on resources/views/checkout/partials/shipping/methods.blade.php
> +            </x-rapidez-ct::input.radio.tile>
Fixed

2025-03-04 15:34 UTC, jordythevulder commented on resources/views/checkout/partials/sidebar/products.blade.php
> +        <button v-if="cart.items.length > 2" class="flex items-center pb-1 gap-1 !border-t-0 !pt-0 hover:underline" @click="toggle">
Yes those are needed because of parent targeting those properties

2025-03-05 10:05 UTC, jordythevulder commented on resources/views/checkout/steps/success.blade.php
> +                <x-rapidez-ct::card.inactive class="!bg-green-400/15 px-7 !py-5 rounded-xl border-b border-black/5">
Yes removed the important from the bg-, the other ones were necessary

2025-03-05 11:59 UTC, Roene-JustBetter requested changes

2025-03-05 11:59 UTC, Roene-JustBetter commented on resources/views/components/input/animated.blade.php
Do we need all the importants here?

2025-03-05 11:59 UTC, Roene-JustBetter commented on resources/views/components/input/select/country.blade.php
We do have a country select in the Rapidez/core do we need it in the checkout theme?

See the core: https://github.com/rapidez/core/blob/master/resources/views/components/input/select/country.blade.php

2025-03-05 11:59 UTC, Roene-JustBetter commented on resources/views/components/input/select/select.blade.php
Can't we use the select from the blade components?

2025-03-05 11:59 UTC, Roene-JustBetter commented on resources/views/components/summary.blade.php
> +        <div class="text-green-700 font-semibold">@{{ discount.amount.value | price }}</div>
Why text green and not primary or another color?

2025-03-05 15:12 UTC, jordythevulder commented on resources/views/components/input/select/select.blade.php
Confira has different styling for the inputs / selects.

2025-03-06 07:59 UTC, JimmyHoenderdaal requested changes

2025-03-06 07:59 UTC, JimmyHoenderdaal commented on resources/views/checkout/partials/buttons/new-address.blade.php
> +<button v-on:click.prevent="toggleEdit" class="flex flex-col items-center justify-center gap-y-2 text-muted font-medium bg rounded-md max-md:hidden">
shouldn't this be a new button?

2025-03-06 07:59 UTC, JimmyHoenderdaal commented on resources/views/components/layout/checkout.blade.php
> +    <x-rapidez-ct::layout.sidebar class="sticky top-0 flex flex-col justify-start max-lg:hidden lg:ml-20 lg:h-screen !space-y-0">
is it necessary to do space-y-0 with important?
does the component have twMerge?

2025-03-06 08:56 UTC, jordythevulder commented on resources/views/checkout/partials/buttons/new-address.blade.php
> +<button v-on:click.prevent="toggleEdit" class="flex flex-col items-center justify-center gap-y-2 text-muted font-medium bg rounded-md max-md:hidden">
Well it's more like a tile. If needed i could create a story for this if wanted.
![image](https://github.com/user-attachments/assets/be843922-d654-4821-95d7-7b76822f864b)

2025-03-06 09:08 UTC, jordythevulder commented on resources/views/components/layout/checkout.blade.php
> +    <x-rapidez-ct::layout.sidebar class="sticky top-0 flex flex-col justify-start max-lg:hidden lg:ml-20 lg:h-screen !space-y-0">
Good one! u removed the important, and added twMerge()

2025-03-18 12:23 UTC, merged